import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {useEffect, useState} from "react";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  let [pageLeave, setPageLeave] = useState(0)

    useEffect(() => {
        //Code works but not when alt tabbing?
        // document.addEventListener("visibilitychange", () => {
        //     if (document.hidden) {
        //         setPageLeave(pageLeave = pageLeave + 1)
        //     }
        // });

        //Code works but not when alt tabbing?
        // document.addEventListener('visibilitychange', e=>{
        //     if (document.visibilityState === 'hidden') {
        //         setPageLeave(pageLeave = pageLeave + 1)
        //     }
        // })

        //Code works but not when alt tabbing?
        // document.addEventListener( 'visibilitychange' , function() {
        //     if (document.hidden) {
        //         setPageLeave(pageLeave = pageLeave + 1)
        //     }
        // }, false)

        //This works with alt tabbing and leaving so this is perfect.
        window.onfocus = () => {
            setPageLeave(pageLeave = pageLeave + 1)
        }
    })


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <p>{pageLeave}</p>
      </main>
    </>
  )
}
